name: Python testing

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python_version: [3.12]
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run typechecking
      run: |
        mypy --strict --exclude 'main\.py' .
    - name: Run tests
      run: |
        coverage run --source=dice_10001 -m pytest
        coverage report -m --skip-covered
